### ISSUE TITLE
lazy-load overload.pm

### ISSUE THREAD

**Issue by FGasper** [Perl-Email-Project/Email-Address#15]
If I sent in a patch, would you accept a lazy-load of overload.pm?

Example of what I mean:
https://metacpan.org/source/FELIPE/Call-Context-0.02/lib/Call/Context.pm

**Comment by rjbs** [comment]
I don't think that example has caused me to understand what you're asking for.

**Comment by FGasper** [comment]
What I mean is not to load overload.pm until there’s actually an instance of the object—i.e., something for overload.pm to do.

For callers who just want to use this module for a pattern-match, overload.pm is overkill.

**Comment by rjbs** [comment]
I know, this has languished… but basically I don't think avoiding loading overload.pm is something I'd merge.
